"""Pydantic schemas for opportunity reports and the Opportunity Score.

Two-layer design:
  - OpportunityReportLLM  — exactly what Claude is asked to produce (reasoning only).
  - OpportunityReport     — the stored/served document, extended with backend-assigned
                            bookkeeping (report_id, overall_score, timestamps).

Scoring: the LLM outputs seven 0-100 sub-scores; the backend computes the
weighted overall score deterministically so the formula is auditable and
tunable without re-prompting. Every dimension is favorability-framed —
100 is always GOOD for a new entrant — so the weighted sum is monotonic
(competition=100 means wide open; build_complexity=100 means trivial to build).
"""

import uuid
from datetime import datetime, timezone
from typing import List, Literal

from pydantic import BaseModel, ConfigDict, Field


class OpportunityScoreBreakdown(BaseModel):
    model_config = ConfigDict(extra="forbid")

    customer_pain: int = Field(
        ge=0, le=100,
        description="How acute and urgent the customer pain is. 100 = customers are actively and desperately seeking a fix.",
    )
    demand: int = Field(
        ge=0, le=100,
        description="Strength of market demand and willingness to pay. 100 = strong validated demand.",
    )
    competition: int = Field(
        ge=0, le=100,
        description="Favorability of the competitive landscape for a NEW entrant. 100 = wide open, no strong incumbents. 0 = saturated, dominated by entrenched players.",
    )
    revenue_potential: int = Field(
        ge=0, le=100,
        description="Realistic revenue ceiling and monetization strength. 100 = large addressable revenue with clear pricing power.",
    )
    trend_growth: int = Field(
        ge=0, le=100,
        description="Growth trajectory of the underlying trend or market. 100 = strong accelerating tailwind.",
    )
    build_complexity: int = Field(
        ge=0, le=100,
        description="Buildability for a solo founder or small team, favorability-framed. 100 = trivial MVP buildable in days. 0 = needs a large team and years.",
    )
    ai_confidence: int = Field(
        ge=0, le=100,
        description="Your own confidence in this analysis given your knowledge of this space. 100 = well-documented domain you know deeply. 0 = highly speculative, sparse signal.",
    )


SCORE_WEIGHTS = {
    "customer_pain": 0.25,
    "demand": 0.20,
    "competition": 0.15,
    "revenue_potential": 0.15,
    "trend_growth": 0.10,
    "build_complexity": 0.10,
    "ai_confidence": 0.05,
}
assert abs(sum(SCORE_WEIGHTS.values()) - 1.0) < 1e-9


def compute_overall_score(breakdown: OpportunityScoreBreakdown) -> int:
    total = sum(getattr(breakdown, key) * weight for key, weight in SCORE_WEIGHTS.items())
    return round(total)


class CustomerProblem(BaseModel):
    model_config = ConfigDict(extra="forbid")
    problem: str
    severity: Literal["low", "medium", "high"]


class EvidencePoint(BaseModel):
    model_config = ConfigDict(extra="forbid")
    point: str
    basis: Literal["reasoning", "known_industry_pattern", "anecdotal_signal"] = Field(
        description="The kind of support behind this point. This product version has no live web access, so be explicit: 'reasoning' for first-principles inference, 'known_industry_pattern' for well-documented dynamics you are confident of, 'anecdotal_signal' for weaker or fragmentary signal.",
    )


class Competitor(BaseModel):
    model_config = ConfigDict(extra="forbid")
    name: str
    description: str
    weakness: str = Field(description="The gap this opportunity can exploit against this competitor.")


class OpportunityReportLLM(BaseModel):
    """The structured object Claude returns. Bookkeeping fields are deliberately
    excluded — the LLM's job is reasoning, not IDs or timestamps."""

    model_config = ConfigDict(extra="forbid")

    executive_summary: str
    customer_problems: List[CustomerProblem]
    evidence: List[EvidencePoint]
    score_breakdown: OpportunityScoreBreakdown
    market_analysis: str
    competitor_analysis: List[Competitor]
    recommended_mvp: str
    pricing_recommendation: str
    go_to_market_plan: str
    build_time_estimate: str


DEFAULT_DISCLAIMER = (
    "Generated by AI reasoning from Claude's training knowledge — not live web "
    "data. Verify demand and competition independently before building."
)


class OpportunityReport(OpportunityReportLLM):
    """The stored and served document: LLM output + backend-assigned fields."""

    report_id: str = Field(default_factory=lambda: f"rpt_{uuid.uuid4().hex[:12]}")
    query: str
    overall_score: int
    model: str
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    disclaimer: str = DEFAULT_DISCLAIMER


class ReportCreateRequest(BaseModel):
    query: str = Field(min_length=3, max_length=200)
